version: "3.8"

services:
  selenium-hub:
    image: selenium/hub:4.23.0
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.23.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_SESSION_TIMEOUT=900  # 15 minutes

  video:
    image: selenium/video:latest
    depends_on:
      - chrome
    environment:
      - DISPLAY_CONTAINER_NAME=chrome
      - FILE_NAME=illphated-session.mp4
    volumes:
      - ./videos:/videos
    stop_grace_period: 10s

  test-runner:
    build: .
    depends_on:
      - selenium-hub
    volumes:
      - .:/tests
    command: >
      sh -c "
        echo 'Waiting for Selenium Hub...' &&
        until nc -z selenium-hub 4444; do sleep 1; done &&
        echo 'Hub is ready! Running script...' &&
        python test_script.py
      "

